# Generated by Django 3.2.3 on 2021-05-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='label',
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
